-- schema.sql

-- Container metrics table
CREATE TABLE IF NOT EXISTS container_metrics (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts INTEGER,
  container_id TEXT,
  cpu_pct REAL,
  mem_used INTEGER,
  mem_limit INTEGER,
  net_rx INTEGER,
  net_tx INTEGER
);

-- Container lifecycle events (start, stop, restart)
CREATE TABLE IF NOT EXISTS container_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts INTEGER,
  container_id TEXT,
  event_type TEXT,
  details TEXT
);

-- Predictions generated by intelligence layer
CREATE TABLE IF NOT EXISTS predictions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts INTEGER,
  container_id TEXT,
  metric TEXT,
  time_to_limit_min REAL,
  explanation TEXT,
  confidence REAL
);

-- Actions performed (restart, stop, etc.)
CREATE TABLE IF NOT EXISTS actions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts INTEGER,
  container_id TEXT,
  action TEXT,
  result TEXT
);
